// ── TRAINING PLAN DATA ─────────────────────────────────────
const PLAN = {
  mon: {
    label:'周一', title:'上肢推力训练', sub:'胸 · 肩 · 三头',
    color:'#0C447C', bg:'#E6F1FB', dotColor:'#378ADD',
    sections:[
      { label:'训练前热身 · 12 分钟', dot:'#888780', type:'warmup', items:[
        '跑步机快走 5 分钟，心率升至 100–110 次/分',
        '肩绕环前后各 20 次 + 手腕绕环 20 次',
        '弹力带肩外旋 15次 × 2组（保护肩袖）',
        '空杆卧推 15次（神经激活）',
        '动态胸肌拉伸：门框撑开 10次',
      ]},
      { label:'胸 · 主力推', dot:'#378ADD', type:'exercises', exercises:[
        { id:'m1', name:'杠铃平板卧推', sets:4, reps:'6–8次', countUnit:'次', rest:150,
          badge:'4组×6–8次', badgeColor:'#0C447C', badgeBg:'#E6F1FB',
          meta:'重量：75–85% 1RM · 组间休息 2–3 分钟',
          tip:'握距略宽于肩，下放时肘部与躯干约 45–60°。底部停顿 1 秒再发力，不要弹起。' },
        { id:'m2', name:'上斜哑铃卧推', sets:3, reps:'10–12次', countUnit:'次', rest:90,
          badge:'3组×10–12次', badgeColor:'#0C447C', badgeBg:'#E6F1FB',
          meta:'坡度 30–45° · 重量中等 · 组间休息 90 秒',
          tip:'哑铃比杠铃活动范围更大，可以更好地拉伸胸肌。推到顶不完全锁肘。' },
        { id:'m3', name:'绳索交叉夹胸', sets:3, reps:'12–15次', countUnit:'次', rest:60,
          badge:'3组×12–15次', badgeColor:'#0C447C', badgeBg:'#E6F1FB',
          meta:'重量：轻–中 · 孤立胸肌 · 组间休息 60 秒',
          tip:'肘部微屈固定，靠胸肌带动手臂合拢，顶峰停顿 1 秒感受收缩。' },
      ]},
      { label:'肩 · 三角肌', dot:'#BA7517', type:'exercises', exercises:[
        { id:'m4', name:'哑铃坐姿肩推', sets:4, reps:'8–10次', countUnit:'次', rest:120,
          badge:'4组×8–10次', badgeColor:'#633806', badgeBg:'#FAEEDA',
          meta:'重量：中–大 · 组间休息 2 分钟',
          tip:'推到顶不完全锁肘，核心收紧不借腰。感受三角肌主导发力。' },
        { id:'m5', name:'侧平举 + 前平举（超级组）', sets:3, reps:'各12次', countUnit:'次', rest:90,
          badge:'3组×各12次', badgeColor:'#633806', badgeBg:'#FAEEDA',
          meta:'侧平举→前平举不休息 · 组间休息 90 秒',
          tip:'超级组：侧平举做完立即接前平举，不休息。重量轻–中，注重感受度。' },
      ]},
      { label:'三头肌', dot:'#378ADD', type:'exercises', exercises:[
        { id:'m6', name:'绳索下压 + 头上三头伸展（超级组）', sets:3, reps:'各12次', countUnit:'次', rest:90,
          badge:'3组×各12次', badgeColor:'#0C447C', badgeBg:'#E6F1FB',
          meta:'下压→头上伸展不休息 · 组间休息 90 秒',
          tip:'两动作分别针对三头肌外侧头和长头。肘部夹紧不外展。' },
      ]},
      { label:'面拉 · 必做', dot:'#1D9E75', type:'exercises', exercises:[
        { id:'m7', name:'绳索面拉（Face Pull）', sets:3, reps:'15次', countUnit:'次', rest:60,
          badge:'3组×15次', badgeColor:'#085041', badgeBg:'#E1F5EE',
          meta:'重量：轻 · 每次上肢训练必做',
          tip:'绳索到面部高度，肘部向外展开，感受后三角和肩袖发力。永远保留这个动作。' },
      ]},
      { label:'有氧 · 20 分钟', dot:'#639922', type:'cardio',
        title:'跑步机 / 椭圆机 · 稳态有氧',
        body:'心率 130–145 次/分（最大心率 65–75%）\n力量训练后有氧优先动用脂肪，减脂效率更高' },
      { label:'训练后拉伸 · 12 分钟', dot:'#BA7517', type:'warmup', items:[
        '胸肌门框拉伸 30s × 2',
        '肩后侧跨体拉伸 30s × 2（每侧）',
        '肱三头过头拉伸 30s × 2（每侧）',
        '颈部侧屈拉伸 30s × 2（每侧）',
        '腕屈伸拉伸 20s × 2（每侧）',
      ]},
    ]
  },
  tue: {
    label:'周二', title:'下肢训练 A', sub:'深蹲主导 · 股四 + 腘绳肌',
    color:'#26215C', bg:'#EEEDFE', dotColor:'#7F77DD',
    sections:[
      { label:'训练前热身 · 12 分钟', dot:'#888780', type:'warmup', items:[
        '骑行机低阻力 5 分钟',
        '臀桥激活 20次 × 2组',
        '弹力带蚌壳式 15次 × 2组（激活臀中肌）',
        '空蹲热身 15次，感受膝盖对齐脚尖',
        '髋屈肌动态拉伸 10次（每侧）',
      ]},
      { label:'深蹲模式 · 股四主导', dot:'#7F77DD', type:'exercises', exercises:[
        { id:'t1', name:'自由杠铃深蹲', sets:4, reps:'5–6次', countUnit:'次', rest:180,
          badge:'4组×5–6次', badgeColor:'#26215C', badgeBg:'#EEEDFE',
          meta:'重量：80–85% 1RM · 组间休息 3 分钟 · 本周最重动作',
          tip:'使用安全架。脚距肩宽，脚尖微外旋，下蹲到大腿平行地面，全程脚跟不离地。' },
        { id:'t2', name:'保加利亚分腿蹲', sets:3, reps:'每侧10次', countUnit:'次', rest:120,
          badge:'3组×每侧10次', badgeColor:'#26215C', badgeBg:'#EEEDFE',
          meta:'哑铃或自重 · 组间休息 2 分钟',
          tip:'单侧训练暴露左右肌力差异。前腿膝盖不超脚尖，后腿放在椅上 40–50cm 高。' },
        { id:'t3', name:'腿举机（中位）', sets:3, reps:'12次', countUnit:'次', rest:90,
          badge:'3组×12次', badgeColor:'#26215C', badgeBg:'#EEEDFE',
          meta:'重量：中–大 · 组间休息 90 秒',
          tip:'脚放中间位置感受股四头肌发力，推到接近伸直不锁膝。' },
      ]},
      { label:'腘绳肌 · 髋铰链', dot:'#1D9E75', type:'exercises', exercises:[
        { id:'t4', name:'罗马尼亚硬拉', sets:4, reps:'8–10次', countUnit:'次', rest:120,
          badge:'4组×8–10次', badgeColor:'#085041', badgeBg:'#E1F5EE',
          meta:'杠铃或哑铃 · 重量中–大 · 组间休息 2 分钟',
          tip:'膝盖微屈固定，髋后推同时上身前倾，感受腘绳肌拉伸后髋前送站起。全程背部中立。' },
        { id:'t5', name:'俯卧腿弯举', sets:3, reps:'12–15次', countUnit:'次', rest:60,
          badge:'3组×12–15次', badgeColor:'#085041', badgeBg:'#E1F5EE',
          meta:'腿弯举机 · 重量轻–中 · 组间休息 60 秒',
          tip:'弯举到顶停顿 1 秒，缓慢放下 3–4 秒感受离心拉伸。不要甩腿。' },
      ]},
      { label:'有氧 · 20 分钟', dot:'#639922', type:'cardio',
        title:'骑行机 / 椭圆机 · 稳态有氧',
        body:'心率 130–145 次/分\n下肢训练后选骑行或椭圆机，避免跑步冲击已疲劳的膝关节' },
      { label:'训练后拉伸 · 12 分钟', dot:'#BA7517', type:'warmup', items:[
        '股四头肌站立拉伸 30s × 2（每侧）',
        '腘绳肌坐姿拉伸 30s × 2',
        '髋屈肌弓步拉伸 30s × 2（每侧）',
        '臀肌鸽子式 30s × 2（每侧）',
        '小腿提踵拉伸 30s × 2',
      ]},
    ]
  },
  thu: {
    label:'周四', title:'上肢拉力训练', sub:'背 · 肱二 · 肩后束 · 前臂',
    color:'#085041', bg:'#E1F5EE', dotColor:'#1D9E75',
    sections:[
      { label:'训练前热身 · 12 分钟', dot:'#888780', type:'warmup', items:[
        '跑步机快走 5 分钟',
        '肩绕环 + 肩胛骨内收外展各 20 次',
        '弹力带肩外旋 15次 × 2组',
        '绳索直臂下压热身 15次（激活背阔肌）',
        '悬挂放松 20–30秒（引体向上杆）',
      ]},
      { label:'背 · 垂直拉', dot:'#1D9E75', type:'exercises', exercises:[
        { id:'h1', name:'引体向上（或辅助引体）', sets:4, reps:'力竭', countUnit:'次', rest:150,
          badge:'4组×力竭', badgeColor:'#085041', badgeBg:'#E1F5EE',
          meta:'自重 / 辅助机 · 组间休息 2–3 分钟 · 组间悬挂练握力',
          tip:'能做 6 次以上用自重，不足 6 次用辅助引体机。用背肌带动手臂，下拉到锁骨。' },
        { id:'h2', name:'高位下拉（宽握）', sets:3, reps:'10–12次', countUnit:'次', rest:90,
          badge:'3组×10–12次', badgeColor:'#085041', badgeBg:'#E1F5EE',
          meta:'重量：中–大 · 组间休息 90 秒',
          tip:'下拉到锁骨停顿 1 秒再缓慢还原，感受背阔肌主导发力。' },
      ]},
      { label:'背 · 水平拉', dot:'#1D9E75', type:'exercises', exercises:[
        { id:'h3', name:'杠铃俯身划船', sets:4, reps:'6–8次', countUnit:'次', rest:120,
          badge:'4组×6–8次', badgeColor:'#085041', badgeBg:'#E1F5EE',
          meta:'重量：中–大 · 组间休息 2 分钟',
          tip:'上身前倾约 45°，背部中立，杠铃拉至肚脐位置。不要靠身体晃动借力。' },
        { id:'h4', name:'单臂哑铃划船', sets:3, reps:'每侧10次', countUnit:'次', rest:90,
          badge:'3组×每侧10次', badgeColor:'#085041', badgeBg:'#E1F5EE',
          meta:'重量：中等 · 膝盖撑椅 · 组间休息 90 秒',
          tip:'肘部高过背部充分收缩，感受菱形肌和背阔肌同时发力。' },
      ]},
      { label:'肱二头肌', dot:'#378ADD', type:'exercises', exercises:[
        { id:'h5', name:'杠铃弯举 + 锤式弯举（超级组）', sets:3, reps:'各10次', countUnit:'次', rest:90,
          badge:'3组×各10次', badgeColor:'#0C447C', badgeBg:'#E6F1FB',
          meta:'正握→中性握不休息 · 组间休息 90 秒',
          tip:'杠铃弯举攻外侧头，锤式弯举攻肱肌和前臂。顶峰停顿 1 秒，缓慢下放。' },
      ]},
      { label:'肩后束 + 面拉', dot:'#BA7517', type:'exercises', exercises:[
        { id:'h6', name:'俯身哑铃飞鸟 + 绳索面拉（超级组）', sets:3, reps:'各15次', countUnit:'次', rest:60,
          badge:'3组×各15次', badgeColor:'#633806', badgeBg:'#FAEEDA',
          meta:'轻量 · 不休息 · 组间休息 60 秒',
          tip:'俯身飞鸟感受肩后束收缩，面拉强化肩袖稳定。雷打不动每次拉力训练必做。' },
      ]},
      { label:'前臂专项 · 10 分钟', dot:'#D85A30', type:'exercises', exercises:[
        { id:'h7', name:'哑铃腕屈曲', sets:3, reps:'15次', countUnit:'次', rest:45,
          badge:'3组×15次', badgeColor:'#712B13', badgeBg:'#FAECE7',
          meta:'重量：2–5kg · 组间休息 45 秒',
          tip:'前臂放大腿上，手心朝上，手腕向上卷起停顿 1 秒，缓慢下放到底感受拉伸。' },
        { id:'h8', name:'哑铃腕伸展', sets:3, reps:'15次', countUnit:'次', rest:45,
          badge:'3组×15次', badgeColor:'#712B13', badgeBg:'#FAECE7',
          meta:'重量：1–3kg · 比腕屈曲轻 · 组间休息 45 秒',
          tip:'前臂放大腿上，手背朝上，手腕向上抬起停顿 1 秒，缓慢下放。预防网球肘复发。' },
      ]},
      { label:'有氧 · 20 分钟', dot:'#639922', type:'cardio',
        title:'跑步机慢跑 / 椭圆机 · 稳态有氧',
        body:'心率 130–145 次/分\n上肢训练后下肢良好，可选跑步机轻松跑' },
      { label:'训练后拉伸 · 12 分钟', dot:'#BA7517', type:'warmup', items:[
        '背阔肌侧拉伸 30s × 2（每侧）',
        '肩后侧跨体拉伸 30s × 2（每侧）',
        '胸椎旋转拉伸 10次（每侧）',
        '肱二头肌拉伸 30s × 2（每侧）',
        '腕伸肌拉伸 30s × 2（掌心向下，另一手压手背）',
        '腕屈肌拉伸 30s × 2（掌心向上，另一手压手指）',
      ]},
    ]
  },
  fri: {
    label:'周五', title:'下肢训练 B', sub:'臀腿主导 · 臀大肌 + 核心',
    color:'#26215C', bg:'#EEEDFE', dotColor:'#7F77DD',
    sections:[
      { label:'训练前热身 · 12 分钟', dot:'#888780', type:'warmup', items:[
        '骑行机低阻力 5 分钟',
        '弹力带蚌壳式 15次 × 2组（激活臀中肌）',
        '仰卧臀桥 20次 × 2组（激活臀大肌）',
        '髋关节绕环 10次 × 2（每侧）',
        '猫牛式腰椎活动 10次',
      ]},
      { label:'臀肌主导', dot:'#7F77DD', type:'exercises', exercises:[
        { id:'f1', name:'杠铃臀推', sets:4, reps:'8–10次', countUnit:'次', rest:120,
          badge:'4组×8–10次', badgeColor:'#26215C', badgeBg:'#EEEDFE',
          meta:'重量：中–大 · 顶峰停顿 2 秒 · 组间休息 2 分钟',
          tip:'杠铃加护垫放髋骨下方，背靠椅沿，推到髋部平行地面，顶峰收缩 2 秒再下放。' },
        { id:'f2', name:'相扑深蹲（宽距）', sets:3, reps:'10–12次', countUnit:'次', rest:90,
          badge:'3组×10–12次', badgeColor:'#26215C', badgeBg:'#EEEDFE',
          meta:'哑铃或杠铃 · 组间休息 90 秒',
          tip:'脚距约 1.5 倍肩宽，脚尖外旋，膝盖跟脚尖方向一致，感受臀部发力。' },
      ]},
      { label:'腿部辅助', dot:'#1D9E75', type:'exercises', exercises:[
        { id:'f3', name:'腿举机（高位宽距）', sets:3, reps:'15次', countUnit:'次', rest:90,
          badge:'3组×15次', badgeColor:'#085041', badgeBg:'#E1F5EE',
          meta:'重量：中等 · 脚放高位宽距 · 组间休息 90 秒',
          tip:'脚放高位偏宽，比周二腿举更多刺激臀肌和腘绳肌，两天形成互补。' },
        { id:'f4', name:'哑铃弓步走', sets:3, reps:'每侧12步', countUnit:'步', rest:90,
          badge:'3组×每侧12步', badgeColor:'#085041', badgeBg:'#E1F5EE',
          meta:'哑铃适当重量 · 走廊进行',
          tip:'前膝不超脚尖，上身挺直。同时消耗热量，减脂期高效动作。' },
      ]},
      { label:'核心', dot:'#378ADD', type:'exercises', exercises:[
        { id:'f5', name:'平板支撑变式（超级组）', sets:3, reps:'45s+各25s', countUnit:'秒', rest:60,
          badge:'3组', badgeColor:'#0C447C', badgeBg:'#E6F1FB',
          meta:'平板支撑 45s → 侧平板 25s（每侧） · 组间休息 60 秒',
          tip:'一组覆盖腹直肌和腹斜肌。侧平板要求腰侧支撑，对腰侧线条有效。' },
        { id:'f6', name:'绳索跪姿卷腹', sets:3, reps:'15次', countUnit:'次', rest:60,
          badge:'3组×15次', badgeColor:'#0C447C', badgeBg:'#E6F1FB',
          meta:'重量：轻–中绳索 · 组间休息 60 秒',
          tip:'以腹肌发力卷曲，不靠髋屈肌代偿。感受腹直肌从上到下收缩。' },
      ]},
      { label:'有氧 · 20 分钟', dot:'#639922', type:'cardio',
        title:'骑行机 / 椭圆机 · 稳态有氧',
        body:'心率 130–145 次/分\n本周最后一次训练，完成后迎接三天休息，尽力做好收尾' },
      { label:'训练后拉伸 · 12 分钟', dot:'#BA7517', type:'warmup', items:[
        '股四头肌站立拉伸 30s × 2（每侧）',
        '腘绳肌坐姿拉伸 30s × 2',
        '臀肌鸽子式 30s × 2（每侧）',
        '髋屈肌跪姿拉伸 30s × 2（每侧）',
        '眼镜蛇式脊柱伸展 30s × 2',
      ]},
    ]
  }
};

const DAY_KEYS = ['mon','tue','thu','fri'];
const DAY_WEEKDAY = { mon:1, tue:2, thu:4, fri:5 };
